name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  tests:
    name: Testing
    strategy:
      matrix:
        python-version: 
          - "3.11"

    runs-on: ubuntu-latest
    steps:
      - name: "Get the repository content"
        uses: actions/checkout@v2

      - name: Enable version ${{ matrix.python-version }} of Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        run: pipx install poetry

      - name: install dependencies
        run:  poetry install

      - name: Check format
        run: poetry run black . --check

      - name: Run tests
        run: poetry run pytest -v
